### ISSUE TITLE
Diseño de la Base de Datos

### ISSUE THREAD

**Issue by PaolaSanchezMedina** [PaolaSanchezMedina/CashControl#1]
Fecha límite 22 de Septiembre de 2023
Diseñar y desarrollar las tablas y relaciones de la base de datos.

**Comment by SoyHadrian** [comment]
![image](https://github.com/PaolaSanchezMedina/CashControl/assets/113461740/dbf9fb8b-9ccc-4d4e-af49-d1ce5abf1dde)

**Comment by SLeonardoCR** [comment]
dc3e423
