### ISSUE TITLE
Interfaces de Usuario

### ISSUE THREAD

**Issue by PaolaSanchezMedina** [PaolaSanchezMedina/CashControl#6]
Desarrollo de Interfaces de Usuario

**Comment by SoyHadrian** [comment]
# Propuesta de interfaces #
* Pantalla principal.
* Inicio de Sesión.
* Pantalla de ingresos/gastos.

![image](https://github.com/PaolaSanchezMedina/CashControl/assets/113461740/2d0748b6-d1b7-452e-8ba0-27828101ca3b)
![image](https://github.com/PaolaSanchezMedina/CashControl/assets/113461740/a7c8c30d-3777-4fc8-a76c-84e347acfc1d)
![image](https://github.com/PaolaSanchezMedina/CashControl/assets/113461740/4223b47c-5436-45e9-b4b1-bc7994e50793)
